AIRPLANE_API = 'http://192.168.0.41:8081'
AIRPLANE_QUEUE = 'Airplane'
PASSENGER_API = 'http://quantum0.pythonanywhere.com'
VISUALIZER_QUEUE = 'visualizer'
UND_ROUTING_KEY = 'gtc.gate'
UND_EXCHANGE = 'amqp.gtc'
BUS_QUEUE = 'Bus'
