AIRPLANE_API = 'Sasha api'
BAGGAGE_API = 'http://dmitryshepelev15.pythonanywhere.com'
BAGGAGE_QUEUE = 'baggage'
PASSENGER_API = 'http://quantum0.pythonanywhere.com'
VISUALIZER_QUEUE = ''
UND_ROUTING_KEY = 'gtc.gate'
UND_EXCHANGE = 'amqp.gtc'
