AIRPLANE_API = 'http://10.99.52.218:8081'
AIRPLANE_QUEUE = 'Airplane'
BAGGAGE_API = 'http://dmitryshepelev15.pythonanywhere.com'
BAGGAGE_QUEUE = 'baggage'
PASSENGER_API = 'http://quantum0.pythonanywhere.com'
VISUALIZER_QUEUE = 'visualizer'
UND_ROUTING_KEY = 'gtc.gate'
UND_EXCHANGE = 'amqp.gtc'
